#language used
language: cpp

#compiler
compiler: gcc

#install:
install:
 - sudo apt-get install binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 binutils-mingw-w64

#build
script: 
 - make all

after_success:
 - echo "Build effettuata con successo" 
