#language used
language: cpp

#compiler
compiler: gcc

#install:
install:
 - sudo apt-get install gcc-mingw-w64-i686 gcc-mingw-w64-x86-x64 g++-mingw-w64-i686 g++-mingw-w64-x86-x64 mingw-w64

#build
script: 
 - make all

after_success:
 - echo "Build effettuata con successo" 
