#language used
language: cpp

#compiler
compiler: gcc

#install:
install:
 - sudo apt-get install mingw-w64

#build
script: 
 - i686-w64-mingw32-gcc --help
 - x86_64-w64-mingw32-gcc --help
 - make all

after_success:
 - echo "Build effettuata con successo" 
