#language used
language: cpp

#compiler
compiler: gcc

#install:
install:
 - sudo apt-get install mingw-w64 gcc-mingw-w64 gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 binutils-mingw-w64 binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 g++-mingw-w64 g++-mingw-w64-i686 g++-mingw-w64-x86-64 

#build
script: 
 #- i686-w64-mingw32-gcc --help
 #- x86_64-w64-mingw32-gcc --help
 - make all

after_success:
 - echo "Build effettuata con successo" 
