
SOURCES=elaboraimmagine.cpp

ADDITIONAL_CFLAGS ?= -g
MACHINE_X86 = i686
MACHINE_X64 = x86_64
RUNNING_MACHINE = w64
ENV = mingw32

CC_WIN_X86 = $(MACHINE_X86)-$(RUNNING_MACHINE)-$(ENV)-$(CXX)
CC_WIN_X64 = $(MACHINE_X64)-$(RUNNING_MACHINE)-$(ENV)-$(CXX)

all: $(RELEASE_WIN32) $(RELEASE_WIN64) $(RELEASE_UNIX32) $(RELEASE_UNIX64)

$(RELEASE_WIN32): $(SOURCES)
	mkdir -p $(RELEASE_WIN32)
	$(CC_WIN_X86) $(ADDITIONAL_CFLAGS) -Wall "$(<)" -o "$(RELEASE_WIN32)/$(RELEASE_NAME).exe"
	
$(RELEASE_WIN64): $(SOURCES)
	mkdir -p $(RELEASE_WIN64)
	$(CC_WIN_X64) $(ADDITIONAL_CFLAGS) -Wall "$(<)" -o "$(RELEASE_WIN64)/$(RELEASE_NAME).exe"

$(RELEASE_UNIX32): $(SOURCES)
	mkdir -p $(RELEASE_UNIX32)
	$(CXX) $(ADDITIONAL_CFLAGS) -m32 -L/usr/lib32 -Wall "$(<)" -o "$(RELEASE_UNIX32)/$(RELEASE_NAME)"
	
$(RELEASE_UNIX64): $(SOURCES)
	mkdir -p $(RELEASE_UNIX64)
	$(CXX) $(ADDITIONAL_CFLAGS) -m64 -Wall "$(<)" -o "$(RELEASE_UNIX64)/$(RELEASE_NAME)"

clean:
	$(RM) -rf $(RELEASE_WIN32)
	$(RM) -rf $(RELEASE_WIN64)
	$(RM) -rf $(RELEASE_UNIX32)
	$(RM) -rf $(RELEASE_UNIX64)